### ISSUE TITLE
Missing steps in GitHub OAuth setup

### ISSUE THREAD

**Issue by dnys1** [googlecodelabs/flutter-github-graphql-client#3]
Hello, I really enjoyed the new Github GraphQL tutorial. Thanks for your hard work!

I was able to get it to work after adjusting a few settings in the Github App created in Step 4. First I enabled the following permissions to "Read-only" (Issues and Pull-Requests):

<img width="746" alt="Screen Shot 2020-07-08 at 2 45 12 PM" src="https://user-images.githubusercontent.com/24740863/86973874-231b4b80-c12a-11ea-945f-d842bec3d305.png">

Second, I installed the App by visiting the "Install" tab and clicking Install for my account.

<img width="1011" alt="Screen Shot 2020-07-08 at 2 45 32 PM" src="https://user-images.githubusercontent.com/24740863/86973943-41814700-c12a-11ea-8e73-8a0c50a05cb3.png">

After this everything worked great!

Not sure if I'm unique in experiencing this so I wanted to share. Thanks!

**Comment by kwalrath** [comment]
@domesticmouse does this issue sound familiar?

**Comment by domesticmouse** [comment]
This looks like you configured a GitHub app, which is different to a GitHub OAuth app.

**Comment by kwalrath** [comment]
If this is a trap others could fall into, perhaps we could have a box (in whatever place people are most likely to notice the problem) on the problem, its symptom(s), and the fix.

**Comment by dnys1** [comment]
I see my mistake. Thanks for the help, you two!

**Comment by domesticmouse** [comment]
@kwalrath if you can suggest what should go in the textbox, I'm more than happy to lgtm it. I'm unsure what it should say at this point.

**Comment by kwalrath** [comment]
Maybe something like this in [Step 4](https://codelabs.developers.google.com/codelabs/flutter-github-graphql-client/#3), just above "In completing Creating an OAuth App...":

----
**Important:** Create a GitHub **OAuth app**, not a GitHub app. 

----

Unrelated Q: should we update the links under "Register a GitHub OAuth application"? E.g. point to https://docs.github.com/en/developers/apps/building-oauth-apps instead of https://developer.github.com/apps/building-oauth-apps/, and https://docs.github.com/en/developers/apps/creating-an-oauth-app instead of https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/?

**Comment by domesticmouse** [comment]
I've updated the codelab with the new GitHub doc links, and added a warning section about creating an OAuth app, not a GitHub app.
